# Generated by Django 2.2.4 on 2019-08-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedResearchObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oricid', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='ipfs')),
            ],
        ),
    ]
