# Generated by Django 2.2.4 on 2019-08-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20190818_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubResearchObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oricid', models.CharField(max_length=100)),
                ('downloadedrepozip', models.FileField(upload_to='github')),
            ],
        ),
    ]
