# Generated by Django 2.2.4 on 2019-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_githubresearchobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubresearchobject',
            name='downloadedrepozip',
            field=models.FileField(blank=True, null=True, upload_to='github'),
        ),
    ]
